cyder/emoji.best

.circleci/config.yml, Gemfile, Gemfile.lock, README.md, spec/rails_helper.rb
close #14 
https://codecov.io/gh/cyder/emojix
=> coverage率を計測

Gemfile, Gemfile.lock, app/controllers/api/v1/users_controller.rb, app/serializers/user_serializer.rb, app/views/api/v1/users/_user.json.jb, app/views/api/v1/users/create.json.jb, config/routes.rb, spec/rails_helper.rb, spec/requests/api/v1/users_spec.rb
close #19 
とりあえずユーザの作成からログイン、jsonを返すとこまで。
エラー関係の処理は大きくなりそうだったので別Issueで。
jsonのはき方はもっといいのがあるかもしれないので、確認して頂けると。
=> signupのapiを作成する

Gemfile, Gemfile.lock, contributing.md, doc/api/v1/users.md, spec/rails_helper.rb, spec/requests/api/v1/users_spec.rb
=> autodocを設定する

app/controllers/api/v1/search_controller.rb, app/models/emoji.rb, app/models/tag.rb, app/views/api/v1/emojis/_emoji.json.jb, app/views/api/v1/search/index.json.jb, config/routes.rb, doc/api/emoji.md, doc/api/search.md, doc/api/user.md, doc/api/v1/search.md, spec/requests/api/v1/search_spec.rb
close #32 
ページングは別Issueで
細かいエラー処理もまだ入れてません。
=> 絵文字を検索できるようにした

.rubocop.yml, app/models/emoji.rb, app/models/user.rb
close #40 
```ruby
hoge.
fuga
```
を
```ruby
hoge
.fuga
```
に
=> rubocopの設定変更

app/controllers/api/v1/base_controller.rb, app/controllers/api/v1/user_sessions_controller.rb, app/models/user.rb, app/views/api/v1/user_sessions/destroy.json.jb, config/routes.rb, doc/api/v1/user_sessions.md, spec/requests/api/v1/user_sessions_spec.rb
close #43
見事coverageが100%まで戻りました。
=> ログアウト用のAPIを実装

app/javascript/app/components/emoji-list.jsx, app/javascript/app/components/emoji.jsx, app/javascript/app/components/header.jsx, app/javascript/app/components/shapes/emoji-list.jsx, app/javascript/app/components/shapes/emoji.jsx, app/javascript/app/containers/app.jsx, app/javascript/app/redux/configure-store.jsx, app/javascript/app/redux/modules/reducer.jsx
close #34
storeの情報を表示してみました。（APIを叩くのは今後）
まだ全然情報が足りてないけどとりあえず。
PropTypesの書き方が怪しい気がする。
=> Emojiの一覧表示

contributing.md
=> Remove text garbling

.eslintrc, app/javascript/app/app.jsx, app/javascript/app/components/css/main.css, app/javascript/app/components/css/normalize.css, app/javascript/app/components/emoji-list.jsx, app/javascript/app/components/emoji.jsx, app/javascript/app/components/shapes/emoji.jsx, app/views/app/index.html.erb, package-lock.json, package.json, yarn.lock
close #60
lintが吠えてるのなんとかしたい…
右上のチェックボックスは別Issueで
ダウンロードのアイコンは @ehnh 待ち
=> emojiの表示デザインを作成

app/javascript/app/actions/emojis.jsx, app/javascript/app/api/index.jsx, app/javascript/app/components/emoji-list.jsx, app/javascript/app/components/header.jsx, app/javascript/app/components/search-form.jsx, app/javascript/app/components/shapes/emoji-list.jsx, app/javascript/app/constants/emojis.jsx, app/javascript/app/containers/app.jsx, app/javascript/app/reducers/emojis.jsx, app/javascript/app/sagas/emojis.jsx
close #59
検索キーワードを含めたurlに遷移すべきかも？
=> キーワード検索できるようにする

app/models/emoji.rb, spec/models/emoji_spec.rb
close #88
スペースは自動でアンダースコアに入れ替えるようにした
=> emoji名を英数字に限定

app/javascript/app/actions/emojis.jsx, app/javascript/app/api/index.jsx, app/javascript/app/components/emoji-list.jsx, app/javascript/app/components/header.jsx, app/javascript/app/components/search-form.jsx, app/javascript/app/components/shapes/emoji-list.jsx, app/javascript/app/containers/app.jsx, app/javascript/app/reducers/emojis.jsx, app/javascript/app/sagas/emojis.jsx
close #79 
うーん、ちょっとごちゃごちゃしてきたかも。
=> emojiを並び替え

Gemfile, Gemfile.lock, app/controllers/api/v1/search_controller.rb, app/models/download_log.rb, config/environments/test.rb, db/migrate/20180701141522_add_column_to_emoji.rb, db/schema.rb, spec/rails_helper.rb
=> N + 1問題を打破した

app/javascript/app/app.jsx, app/javascript/app/store.jsx, package.json, yarn.lock
=> ダウンロードカートをクッキーに入れる

app/javascript/app/actions/myself.jsx, app/javascript/app/api/index.jsx, app/javascript/app/constants/myself.jsx, app/javascript/app/containers/sign-up-popup.jsx, app/javascript/app/reducers/myself.jsx, app/javascript/app/sagas/myself.jsx
=> sign upできるようにした

app/javascript/app/store.jsx
=> userの情報を保存するようにした

app/controllers/api/v1/emojis_controller.rb, app/views/api/v1/emojis/show.json.jb, config/routes.rb, doc/api/v1/emoji.md, spec/requests/api/v1/emoji_spec.rb
=> emoji情報の取得

app/javascript/app/actions/emojis.jsx, app/javascript/app/api/index.jsx, app/javascript/app/components/emoji-detail.jsx, app/javascript/app/components/emoji-list.jsx, app/javascript/app/components/shapes/emoji-list.jsx, app/javascript/app/components/shapes/emoji.jsx, app/javascript/app/components/tags.jsx, app/javascript/app/containers/emoji-detail-popup.jsx, app/javascript/app/containers/main-content.jsx, app/javascript/app/reducers/emojis.jsx, app/javascript/app/sagas/emojis.jsx, db/seeds.rb
close #121
* タグの一覧を表示
* タグをクリックしたらタグ検索に飛ぶように
* タグ検索時に見出しが変わるように
=> 詳細画面にタグを表示

app/javascript/app/history.jsx, package.json, yarn.lock
=> googleアナリティクスを導入

app/javascript/app/actions/emojis.jsx, app/javascript/app/api/index.jsx
=> 検索が正しく行われないバグを修正

app/javascript/app/api/index.jsx
close #163
nullが送信されていた。これはまずい。
=> accessTokenが指定されてないときにnullが送信されるのを修正

app/javascript/app/actions/emoji.jsx, app/javascript/app/api/index.jsx, app/javascript/app/components/emoji-detail.jsx, app/javascript/app/components/tags.jsx, app/javascript/app/constants/emoji.jsx, app/javascript/app/containers/emoji-detail-popup.jsx, app/javascript/app/reducers/emoji.jsx, app/javascript/app/sagas/emoji.jsx
=> タグを編集できるようにした

app/controllers/api/v1/download_controller.rb
=> s3にアップロードされた画像をダウンロードできないバグを修正

app/views/layouts/application.html.erb
=> google AdSenseのタグを追加

app/views/layouts/application.html.erb
=> development → master

Dockerfile, README.md, config/database.yml, contributing.md, docker-compose.yml
close #29
readmeを見ながら問題なく環境を作れるか確認して下さい。
=> docker composerで開発環境の構築

app/javascript/app/components/atoms/buttons/circle-button.jsx, app/javascript/app/components/atoms/icons/check.jsx, app/javascript/app/components/emoji-detail.jsx, app/javascript/app/components/emoji.jsx, app/javascript/app/components/molecules/buttons/download-checkbox.jsx, app/javascript/app/constants/styles/color.jsx
=> ダウンロードボタンをコンポーネント化

app/javascript/app/components/download-cart.jsx, app/javascript/app/components/emoji-detail-info.jsx, app/javascript/app/components/emoji.jsx, app/javascript/app/components/shapes/emoji.jsx, app/javascript/app/components/upload-emoji.jsx, app/uploaders/emoji_uploader.rb, app/views/api/v1/emojis/_emoji.json.jb
=> 横長の絵文字のリサイズ方法をSlackに合わせた

app/javascript/app/components/atoms/emojis/emoji-img.jsx, app/javascript/app/components/download-cart.jsx, app/javascript/app/components/emoji-detail-info.jsx, app/javascript/app/components/emoji.jsx, app/javascript/app/components/upload-emoji.jsx
close #205
imgタグに変更するのはいろいろとブラウザサポートがたりなさそう
https://caniuse.com/#feat=object-fit
https://caniuse.com/#search=pointer-events
=> emoji画像のコンポーネントを統一

config/initializers/carrierwave.rb
=> [fix] carrierwaveの設定が間違っていた

app/javascript/app/api/emoji.js, config/routes.rb, spec/requests/api/v1/donwlod_spec.rb
google等のbotに勝手にクロールさせないため
close #232
=> ダウンロードのAPIをgetからpostにした

README.md, app/javascript/app/components/sns-oauth.jsx, spec/requests/api/v1/emoji_spec.rb
emoji.best -> emoji-best.cyder.jp
=> [change] ドメインの変更

app/javascript/app/components/upload-emoji.jsx, app/javascript/app/containers/upload-popup.jsx
close #239
アップロードボタンを押したときに表示が変わらず、アップロード中かわからなかったのでアップロード中のUIを作成した
送信前|送信中
:--:|:--:
=> アップロード中のUIを追加する
